//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cajero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATM_TRANSACTION
    {
        public int Card_Number_ID { get; set; }
        public string TRANS_NO { get; set; }
        public System.DateTime TRANSACTION_DT { get; set; }
        public int ID_ATM_CD { get; set; }
        public string TRANSACTION_TYPE_NM { get; set; }
        public int TRANSACTION_AMT { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual MAQUINA MAQUINA { get; set; }
    }
}
