//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cajero.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATMDBEntities : DbContext
    {
        public ATMDBEntities()
            : base("name=ATMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADORs { get; set; }
        public virtual DbSet<MAQUINA> MAQUINAs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<ATM_TRANSACTION> ATM_TRANSACTION { get; set; }
        public virtual DbSet<DETALLE_MONEDA> DETALLE_MONEDA { get; set; }
    }
}
