//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cajero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.ATM_TRANSACTION = new HashSet<ATM_TRANSACTION>();
        }
    
        public int Card_Number_ID { get; set; }
        public int ACCOUNT_USER_CD { get; set; }
        public int USER_PIN_CD { get; set; }
        public string CEDULA_CD { get; set; }
        public string ACCOUNT_TYPE_DESC { get; set; }
        public int BALANCE_USER_STOCK_AMT { get; set; }
        public int BALANCE_USER_CURRENT_AMT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATM_TRANSACTION> ATM_TRANSACTION { get; set; }
    }
}
